### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by tommygebru** [LauraGitGit/Tea-Cozy#3]
_Notes aren't only for yourself but for others who visit your project and wish to contribute, help, copy or review 😉_ 

Consider using commenting in both your HTML and CSS documents, this provides a high-level of organization and note-taking. 

Introduce more clarity early at the beginning of your project to create a guideline and narrative.
As you build out more complex webpages and projects, comments can help break down sections and problem solve. 👍

**Comment by LauraGitGit** [comment]
Thats my issue here. Thanks for pointing out!
